stages:
   - build
   - test

build-job:
   stage: build
   script:
      - echo "Check python version and build the project"
      - image: docker pull python
      - pip install -r requirements.txt

test-code:
        stage: test
        script:
        - echo "Executing the test"
        - python test.py


